[project]
name = "comfyui-alchemine-pack"
description = """Prompt filterings, Danbooru, LLM(Inference), API, lazy execution nodes, etc.
[a/Prompt](https://github.com/alchemine/comfyui-alchemine-pack/blob/main/workflows/comfyui-alchemine-pack-workflow-Prompt.png): filtering, token analyzing, auto BREAK, prompt processors
[a/Danbooru](https://github.com/alchemine/comfyui-alchemine-pack/blob/main/workflows/comfyui-alchemine-pack-workflow-Danbooru.png): tag and post retriever
[a/Inference](https://github.com/alchemine/comfyui-alchemine-pack/blob/main/workflows/comfyui-alchemine-pack-workflow-Inference.png): OpenAI-compatible API Inference
[a/API](https://github.com/alchemine/comfyui-alchemine-pack/blob/main/workflows/comfyui-alchemine-pack-workflow-API.png): remote ComfyUI API execution
[a/FlowControl](https://github.com/alchemine/comfyui-alchemine-pack/blob/main/workflows/comfyui-alchemine-pack-workflow-FlowControl.png): lazy execution
Python evaluate, Grok, Cached LoRA Tag loader, etc."""

version = "2.4.1"
license = { file = "LICENSE" }
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.0.0",
]

[project.urls]
Repository = "https://github.com/alchemine/comfyui-alchemine-pack"
# Documentation = "https://github.com/alchemine/comfyui-alchemine-pack/wiki"
"Bug Tracker" = "https://github.com/alchemine/comfyui-alchemine-pack/issues"

[tool.comfy]
PublisherId = "alchemine"
DisplayName = "ComfyUI-Alchemine-Pack"
Icon = ""
